<?php
/**
 * HamstraAPIModelsOrdersOrderLineTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Horrentotaal\Hamstra
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Hamstra API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.32
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Horrentotaal\Hamstra;

/**
 * HamstraAPIModelsOrdersOrderLineTest Class Doc Comment
 *
 * @category    Class
 * @description HamstraAPIModelsOrdersOrderLine
 * @package     Horrentotaal\Hamstra
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class HamstraAPIModelsOrdersOrderLineTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "HamstraAPIModelsOrdersOrderLine"
     */
    public function testHamstraAPIModelsOrdersOrderLine()
    {
    }

    /**
     * Test attribute "order_line_id"
     */
    public function testPropertyOrderLineId()
    {
    }

    /**
     * Test attribute "order_id"
     */
    public function testPropertyOrderId()
    {
    }

    /**
     * Test attribute "sales_line_id"
     */
    public function testPropertySalesLineId()
    {
    }

    /**
     * Test attribute "order_line_ref_nr"
     */
    public function testPropertyOrderLineRefNr()
    {
    }

    /**
     * Test attribute "quantity_ordered"
     */
    public function testPropertyQuantityOrdered()
    {
    }

    /**
     * Test attribute "sales_item_id"
     */
    public function testPropertySalesItemId()
    {
    }

    /**
     * Test attribute "product_id"
     */
    public function testPropertyProductId()
    {
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
    }

    /**
     * Test attribute "line_summary"
     */
    public function testPropertyLineSummary()
    {
    }

    /**
     * Test attribute "line_summary_localized"
     */
    public function testPropertyLineSummaryLocalized()
    {
    }

    /**
     * Test attribute "consumer_price"
     */
    public function testPropertyConsumerPrice()
    {
    }

    /**
     * Test attribute "purchase_price"
     */
    public function testPropertyPurchasePrice()
    {
    }

    /**
     * Test attribute "sales_price"
     */
    public function testPropertySalesPrice()
    {
    }

    /**
     * Test attribute "discount_pct"
     */
    public function testPropertyDiscountPct()
    {
    }

    /**
     * Test attribute "line_amount"
     */
    public function testPropertyLineAmount()
    {
    }

    /**
     * Test attribute "huss_order_line_nr"
     */
    public function testPropertyHussOrderLineNr()
    {
    }

    /**
     * Test attribute "purchase_order_line_nr"
     */
    public function testPropertyPurchaseOrderLineNr()
    {
    }

    /**
     * Test attribute "conversion_interface_nr"
     */
    public function testPropertyConversionInterfaceNr()
    {
    }

    /**
     * Test attribute "height"
     */
    public function testPropertyHeight()
    {
    }

    /**
     * Test attribute "width"
     */
    public function testPropertyWidth()
    {
    }

    /**
     * Test attribute "color"
     */
    public function testPropertyColor()
    {
    }

    /**
     * Test attribute "original_sales_price"
     */
    public function testPropertyOriginalSalesPrice()
    {
    }

    /**
     * Test attribute "discount_hos"
     */
    public function testPropertyDiscountHos()
    {
    }

    /**
     * Test attribute "order_id_spec"
     */
    public function testPropertyOrderIdSpec()
    {
    }

    /**
     * Test attribute "ax_order_nr_per_line"
     */
    public function testPropertyAxOrderNrPerLine()
    {
    }

    /**
     * Test attribute "delivery_week"
     */
    public function testPropertyDeliveryWeek()
    {
    }

    /**
     * Test attribute "extra_delivery_days"
     */
    public function testPropertyExtraDeliveryDays()
    {
    }

    /**
     * Test attribute "customer_description"
     */
    public function testPropertyCustomerDescription()
    {
    }

    /**
     * Test attribute "customer_reference"
     */
    public function testPropertyCustomerReference()
    {
    }

    /**
     * Test attribute "fixed_price"
     */
    public function testPropertyFixedPrice()
    {
    }

    /**
     * Test attribute "ext_bruto_price"
     */
    public function testPropertyExtBrutoPrice()
    {
    }

    /**
     * Test attribute "order_line_options"
     */
    public function testPropertyOrderLineOptions()
    {
    }

    /**
     * Test attribute "calculated_price"
     */
    public function testPropertyCalculatedPrice()
    {
    }

    /**
     * Test attribute "product_name"
     */
    public function testPropertyProductName()
    {
    }
}
