<?php
/**
 * HamstraAPIModelsGridListHamstraAPIModelsQuotationsViewQuotationTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Horrentotaal\Hamstra
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Hamstra API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.32
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Horrentotaal\Hamstra;

/**
 * HamstraAPIModelsGridListHamstraAPIModelsQuotationsViewQuotationTest Class Doc Comment
 *
 * @category    Class
 * @description HamstraAPIModelsGridListHamstraAPIModelsQuotationsViewQuotation
 * @package     Horrentotaal\Hamstra
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class HamstraAPIModelsGridListHamstraAPIModelsQuotationsViewQuotationTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "HamstraAPIModelsGridListHamstraAPIModelsQuotationsViewQuotation"
     */
    public function testHamstraAPIModelsGridListHamstraAPIModelsQuotationsViewQuotation()
    {
    }

    /**
     * Test attribute "current_page"
     */
    public function testPropertyCurrentPage()
    {
    }

    /**
     * Test attribute "total_page_count"
     */
    public function testPropertyTotalPageCount()
    {
    }

    /**
     * Test attribute "total_item_count"
     */
    public function testPropertyTotalItemCount()
    {
    }

    /**
     * Test attribute "page_size"
     */
    public function testPropertyPageSize()
    {
    }

    /**
     * Test attribute "items"
     */
    public function testPropertyItems()
    {
    }
}
