<?php
/**
 * HamstraAPIModelsProductsProductConfigOptionTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Hamstra API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.32
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * HamstraAPIModelsProductsProductConfigOptionTest Class Doc Comment
 *
 * @category    Class
 * @description HamstraAPIModelsProductsProductConfigOption
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class HamstraAPIModelsProductsProductConfigOptionTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "HamstraAPIModelsProductsProductConfigOption"
     */
    public function testHamstraAPIModelsProductsProductConfigOption()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "option"
     */
    public function testPropertyOption()
    {
    }

    /**
     * Test attribute "display_name"
     */
    public function testPropertyDisplayName()
    {
    }

    /**
     * Test attribute "type_id"
     */
    public function testPropertyTypeId()
    {
    }

    /**
     * Test attribute "is_required"
     */
    public function testPropertyIsRequired()
    {
    }

    /**
     * Test attribute "is_valid"
     */
    public function testPropertyIsValid()
    {
    }

    /**
     * Test attribute "validation_message"
     */
    public function testPropertyValidationMessage()
    {
    }

    /**
     * Test attribute "is_enabled"
     */
    public function testPropertyIsEnabled()
    {
    }

    /**
     * Test attribute "read_only_text"
     */
    public function testPropertyReadOnlyText()
    {
    }

    /**
     * Test attribute "product_option_group_id"
     */
    public function testPropertyProductOptionGroupId()
    {
    }

    /**
     * Test attribute "measurement_instructions"
     */
    public function testPropertyMeasurementInstructions()
    {
    }

    /**
     * Test attribute "measurement_image_reference"
     */
    public function testPropertyMeasurementImageReference()
    {
    }

    /**
     * Test attribute "value"
     */
    public function testPropertyValue()
    {
    }

    /**
     * Test attribute "values"
     */
    public function testPropertyValues()
    {
    }
}
