<?php
/**
 * HamstraAPIModelsOrdersOrderQuotationTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Hamstra API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.32
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * HamstraAPIModelsOrdersOrderQuotationTest Class Doc Comment
 *
 * @category    Class
 * @description HamstraAPIModelsOrdersOrderQuotation
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class HamstraAPIModelsOrdersOrderQuotationTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "HamstraAPIModelsOrdersOrderQuotation"
     */
    public function testHamstraAPIModelsOrdersOrderQuotation()
    {
    }

    /**
     * Test attribute "quotation_ids"
     */
    public function testPropertyQuotationIds()
    {
    }

    /**
     * Test attribute "commission_name"
     */
    public function testPropertyCommissionName()
    {
    }

    /**
     * Test attribute "purchase_order"
     */
    public function testPropertyPurchaseOrder()
    {
    }

    /**
     * Test attribute "home_delivery"
     */
    public function testPropertyHomeDelivery()
    {
    }

    /**
     * Test attribute "delivery_name"
     */
    public function testPropertyDeliveryName()
    {
    }

    /**
     * Test attribute "delivery_street"
     */
    public function testPropertyDeliveryStreet()
    {
    }

    /**
     * Test attribute "delivery_zip_code"
     */
    public function testPropertyDeliveryZipCode()
    {
    }

    /**
     * Test attribute "delivery_city"
     */
    public function testPropertyDeliveryCity()
    {
    }

    /**
     * Test attribute "delivery_country"
     */
    public function testPropertyDeliveryCountry()
    {
    }

    /**
     * Test attribute "delivery_email"
     */
    public function testPropertyDeliveryEmail()
    {
    }

    /**
     * Test attribute "delivery_phone"
     */
    public function testPropertyDeliveryPhone()
    {
    }
}
