<?php
/**
 * HamstraAPIModelsProductsProductTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Horrentotaal\Hamstra
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Hamstra API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.32
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Horrentotaal\Hamstra;

/**
 * HamstraAPIModelsProductsProductTest Class Doc Comment
 *
 * @category    Class
 * @description HamstraAPIModelsProductsProduct
 * @package     Horrentotaal\Hamstra
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class HamstraAPIModelsProductsProductTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "HamstraAPIModelsProductsProduct"
     */
    public function testHamstraAPIModelsProductsProduct()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "is_customized_product"
     */
    public function testPropertyIsCustomizedProduct()
    {
    }

    /**
     * Test attribute "has_parts"
     */
    public function testPropertyHasParts()
    {
    }

    /**
     * Test attribute "price"
     */
    public function testPropertyPrice()
    {
    }

    /**
     * Test attribute "in_stock"
     */
    public function testPropertyInStock()
    {
    }

    /**
     * Test attribute "code"
     */
    public function testPropertyCode()
    {
    }
}
