<?php
/**
 * MicrosoftWin32SafeHandlesSafeWaitHandleTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Hamstra API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.32
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * MicrosoftWin32SafeHandlesSafeWaitHandleTest Class Doc Comment
 *
 * @category    Class
 * @description MicrosoftWin32SafeHandlesSafeWaitHandle
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class MicrosoftWin32SafeHandlesSafeWaitHandleTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "MicrosoftWin32SafeHandlesSafeWaitHandle"
     */
    public function testMicrosoftWin32SafeHandlesSafeWaitHandle()
    {
    }

    /**
     * Test attribute "is_invalid"
     */
    public function testPropertyIsInvalid()
    {
    }

    /**
     * Test attribute "is_closed"
     */
    public function testPropertyIsClosed()
    {
    }
}
