<?php
/**
 * ProductApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Horrentotaal\HamstraApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Hamstra API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.32
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Horrentotaal\HamstraApi;

use \Horrentotaal\HamstraApi\Configuration;
use \Horrentotaal\HamstraApi\ApiException;
use \Horrentotaal\HamstraApi\ObjectSerializer;

/**
 * ProductApiTest Class Doc Comment
 *
 * @category Class
 * @package  Horrentotaal\HamstraApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ProductApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for productGetAvailableProducts
     *
     * Get the available products for the authenticated user.
     *
     */
    public function testProductGetAvailableProducts()
    {
    }

    /**
     * Test case for productGetById
     *
     * Get the details of a given product.
     *
     */
    public function testProductGetById()
    {
    }

    /**
     * Test case for productGetBySku
     *
     * Get the product by product code.
     *
     */
    public function testProductGetBySku()
    {
    }

    /**
     * Test case for productGetConfigurationAsync
     *
     * .
     *
     */
    public function testProductGetConfigurationAsync()
    {
    }

    /**
     * Test case for productGetConfigurationAsync_0
     *
     * .
     *
     */
    public function testProductGetConfigurationAsync0()
    {
    }

    /**
     * Test case for productGetValidationMessagesAsync
     *
     * Get the product option validation messages.
     *
     */
    public function testProductGetValidationMessagesAsync()
    {
    }
}
