<?php
/**
 * QuotationApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Horrentotaal\Hamstra
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Hamstra API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.32
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Horrentotaal\Hamstra;

use \Horrentotaal\Hamstra\Configuration;
use \Horrentotaal\Hamstra\ApiException;
use \Horrentotaal\Hamstra\ObjectSerializer;

/**
 * QuotationApiTest Class Doc Comment
 *
 * @category Class
 * @package  Horrentotaal\Hamstra
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class QuotationApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for quotationDeleteQuotation
     *
     * Delete a quotation.
     *
     */
    public function testQuotationDeleteQuotation()
    {
    }

    /**
     * Test case for quotationGetQuotationLines
     *
     * Get the quotation lines by a given quotations.
     *
     */
    public function testQuotationGetQuotationLines()
    {
    }

    /**
     * Test case for quotationGetQuotations
     *
     * Get the quotations.
     *
     */
    public function testQuotationGetQuotations()
    {
    }
}
